// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A flow that suggests improvements to a transport request.
 *
 * - suggestTransportImprovements - A function that suggests improvements to a transport request.
 * - SuggestTransportImprovementsInput - The input type for the suggestTransportImprovements function.
 * - SuggestTransportImprovementsOutput - The return type for the suggestTransportImprovements function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestTransportImprovementsInputSchema = z.object({
  transportType: z.string().describe('The type of transport needed (e.g., passenger, cargo).'),
  origin: z.string().describe('The origin location of the transport.'),
  destination: z.string().describe('The destination location of the transport.'),
  dates: z.string().describe('The desired dates for the transport.'),
  specialRequirements: z.string().describe('Any special requirements for the transport.'),
});
export type SuggestTransportImprovementsInput = z.infer<
  typeof SuggestTransportImprovementsInputSchema
>;

const SuggestTransportImprovementsOutputSchema = z.object({
  suggestedImprovements: z
    .string()
    .describe('Suggestions to improve the transport request.'),
});
export type SuggestTransportImprovementsOutput = z.infer<
  typeof SuggestTransportImprovementsOutputSchema
>;

export async function suggestTransportImprovements(
  input: SuggestTransportImprovementsInput
): Promise<SuggestTransportImprovementsOutput> {
  return suggestTransportImprovementsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'suggestTransportImprovementsPrompt',
  input: {schema: SuggestTransportImprovementsInputSchema},
  output: {schema: SuggestTransportImprovementsOutputSchema},
  prompt: `You are an AI assistant specialized in optimizing transport requests. Analyze the following transport request and suggest improvements to increase the likelihood of finding a suitable match. Focus on aspects like date flexibility, alternative transport types, and clarity of special requirements.

Transport Type: {{{transportType}}}
Origin: {{{origin}}}
Destination: {{{destination}}}
Dates: {{{dates}}}
Special Requirements: {{{specialRequirements}}}

Provide concise and actionable suggestions.
`,
});

const suggestTransportImprovementsFlow = ai.defineFlow(
  {
    name: 'suggestTransportImprovementsFlow',
    inputSchema: SuggestTransportImprovementsInputSchema,
    outputSchema: SuggestTransportImprovementsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
